#!/bin/bash

echo "Meow."

IS_MAC=(`uname` == 'Darwin')
CURRENT_DIR=`pwd`


# Should be automeowtic.
ln -sf  "${CURRENT_DIR}/.zshrc" "${HOME}/.zshrc"
ln -sf  "${CURRENT_DIR}/.p10k.zsh" "${HOME}/.p10k.zsh"
